d3_cpi:
  css: css/local.css
  jshead: [js/d3.v3.js,js/lodash.js]
  cdn:
    jshead:
      - "http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.1/angular.min.js"
      - "http://d3js.org/d3.v3.js"
      - "http://cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.js"
    css:
      - "http://timelyportfolio.github.io/rCharts_d3_cpi/css/local.css"
