d3_cpi:
  jshead:
    - ./js/d3.v3.js
    - ./js/lodash.js
  css:
    - ./css/local.css
  cdn:
    jshead:
      - http://d3js.org/d3.v3.js
      - http://cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.js
    css:
      - http://timelyportfolio.github.io/rCharts_d3_cpi/local.css
